# Generated by Django 4.2.6 on 2023-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_from", models.CharField(max_length=3)),
                ("currency_to", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
