# Generated by Django 4.2.6 on 2023-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rate",
            name="rate",
        ),
        migrations.AddField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
