# Generated by Django 4.2.6 on 2023-10-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0002_remove_rate_rate_rate_buy_rate_sell"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="provider",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
